### ISSUE TITLE
Android staging build splash screen did not disappear

### ISSUE THREAD

**Issue by taminhtien** [zoontek/react-native-bootsplash#14]
### 💻 My environment

- react-native-bootsplash version: 0.1.1
- react-native version: 0.60.4
- Platform: android
- OS version: 9
- Device: Pixel 1
- Simulator: Simulator work
- Android Studio version: 3.4.1
- Android buildToolsVersion: 28.0.3
- Xcode version: iOS work

### 🕵️‍♂️ Reproducing the issue

app/android/build.gradle

```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "MY_APPLICATION_ID"
        minSdkVersion 23
        targetSdkVersion 26
        versionCode 182
        versionName "2.0.0"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
        vectorDrawables.useSupportLibrary = true
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword '123123123'
            keyAlias 'debug'
            keyPassword '123123123'
        }
        release {
            if (project.hasProperty('APP_RELEASE_STORE_FILE')) {
                storeFile file(APP_RELEASE_STORE_FILE)
                storePassword APP_RELEASE_STORE_PASSWORD
                keyAlias APP_RELEASE_KEY_ALIAS
                keyPassword APP_RELEASE_KEY_PASSWORD
            }
        }
    }
     buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
       // Add Build type staging
        staging { 
            applicationIdSuffix ".staging"
            matchingFallbacks = ['release']
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.htmlhttp://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }

    packagingOptions {
        pickFirst '**/armeabi-v7a/libc++_shared.so'
        pickFirst '**/x86/libc++_shared.so'
        pickFirst '**/arm64-v8a/libc++_shared.so'
        pickFirst '**/x86_64/libc++_shared.so'
        pickFirst '**/x86/libjsc.so'
        pickFirst '**/armeabi-v7a/libjsc.so'
    }
}
```

Then build the staging build using Android Studio. After that, install the api in real device. 

#### Expected behaviour:

Boot splash screen disappear and show my app main screen.

#### Actually happens:

The boot splash did not disappear after long waiting time.

Here are the log from Logcat:

```
2019-08-13 17:10:10.967 878-913/? W/BroadcastQueue: Background execution not allowed: receiving Intent { act=com.google.android.systemui.OPA_ENABLED flg=0x10000010 (has extras) } to com.google.android.apps.nexuslauncher/.qsb.OPAStatusReceiver
2019-08-13 17:10:23.650 32658-32658/? E/mberapp.stagin: Not starting debugger since process cannot load the jdwp agent.
2019-08-13 17:10:23.767 32658-32658/? W/com.facebook.UserSettingsManager: Please set a value for AutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
2019-08-13 17:10:23.767 32658-32658/? W/com.facebook.UserSettingsManager: You haven't set a value for AdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-android#disable-auto-events.
2019-08-13 17:10:23.865 32658-32658/? W/System.err: java.lang.ClassNotFoundException: MY_APPLICATION_ID.staging.MainActivity
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at java.lang.Class.classForName(Native Method)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at java.lang.Class.forName(Class.java:453)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at java.lang.Class.forName(Class.java:378)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at com.zoontek.rnbootsplash.RNBootSplashActivity.onCreate(RNBootSplashActivity.java:15)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.app.Activity.performCreate(Activity.java:7144)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.app.Activity.performCreate(Activity.java:7135)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.os.Looper.loop(Looper.java:193)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6718)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-08-13 17:10:23.865 32658-32658/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-08-13 17:10:23.866 32658-32658/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "MY_APPLICATION_ID.staging.MainActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/MY_APPLICATION_ID.staging-gadIS1fm0tvapmwDqwGyiA==/base.apk"],nativeLibraryDirectories=[/data/app/MY_APPLICATION_ID.staging-gadIS1fm0tvapmwDqwGyiA==/lib/arm64, /data/app/MY_APPLICATION_ID.staging-gadIS1fm0tvapmwDqwGyiA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
2019-08-13 17:10:23.866 32658-32658/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
2019-08-13 17:10:23.866 32658-32658/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2019-08-13 17:10:23.866 32658-32658/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2019-08-13 17:10:23.866 32658-32658/? W/System.err: 	... 19 more
2019-08-13 17:10:24.169 491-595/? W/SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen MY_APPLICATION_ID.staging#0
2019-08-13 17:10:24.170 491-595/? W/SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen MY_APPLICATION_ID.staging#0
2019-08-13 17:10:24.378 32507-32567/? W/SearchServiceCore: Abort, client detached.
```

I noted that this [line](https://github.com/zoontek/react-native-bootsplash/blob/master/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java#L15) will return `MY_APPLICATION_ID.staging.MainActivity`, which is not existed in the source code. The source code only have `MY_APPLICATION_ID.MainActivity.java` file.

So my concern is this is expected behaviour? This lib does not support multiple build type? If it is expected behaviour, any workaround to make it work?

Last time I use `react-native-splash-screen` lib, it works well for both staging and release builds.

Thank you.

**Comment by shwanton** [comment]
I'm seeing this same behavior. When I try to build for a specific environment/flavor, the splash screen will dismiss itselft the first time after launched by the gradle task. However, when I manually launch the app the splash screen hangs and the js bundle never loads. I'm using an `applicationIdSuffix` for dev & staging. Both of those have the issue however my production build which just uses the plain bundleId works fine & can be relaunched without hanging.

```
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    flavorDimensions "version"
    productFlavors {
        development {
            dimension "version"
            applicationIdSuffix ".dev"
        }
        staging {
            dimension "version"
            applicationIdSuffix ".beta"
        }
        production {
            dimension "version"
        }
    }
```

**Comment by shwanton** [comment]
I confirmed this issue by checking the generated `MainActivity` Class name [here](https://github.com/zoontek/react-native-bootsplash/blob/master/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java#L15). It was returning the entire identifier which included the `applicationIdSuffix`. (`com.example.foo.beta`)

I have a [fix](https://github.com/shwanton/react-native-bootsplash/commit/b81d0e5c9502b6f7d7c58f36e1ba55533217729d) which requires exposing the `defaultConfig.applicationId` from the gradle file. Since I already had this value from [react native config](https://github.com/luggit/react-native-config#advanced-android-setup), I just had to look it up the `applicationId` inside `RNBootSplashActivity.java` and use that to create the Class name.

I thought I could use the `BuildConfig.APPLICATION_ID`, however that value returns the id for the library bundle, not the root RN app. The solution came from this [comment on SO](https://stackoverflow.com/questions/21365928/gradle-how-to-use-buildconfig-in-an-android-library-with-a-flag-that-gets-set/31587838#31587838)

`app/build.gradle`
```gradle

def appId = "com.example.foo"

defaultConfig {
   applicationId appId
   ...
   resValue "string", "build_config_package", appId
}
```

`RNBootSplashActivity.java`
```java
int resId = this.getResources().getIdentifier("build_config_package", "string", this.getPackageName());
Intent intent = new Intent(this, Class.forName(this.getString(resId) + ".MainActivity"));
```

I'm not sure this is the best/cleanest solution, since it requires an addition to the `app/build.gradle` file. But it does fix this issue.

**Comment by shwanton** [comment]
@zoontek Is multiple environments something you would like to support in this library? I can add a PR with an updated example. It will add a couple more steps to the android process. The biggest change is that you can't fun `react-native run-android` by itself anymore, you will have to pass the variant as well:

`react-native run-android --variant=DevelopmentDebug`

**Comment by zoontek** [comment]
@shwanton Your issue seems related to https://github.com/zoontek/react-native-bootsplash/issues/8 Will the meta-data solution be good enough?

What do you mean by supporting multiple environments? Displaying a different splash screen per env variant?

**Comment by andrewkslv** [comment]
I bump into the same issue since I'm using `applicationIdSuffix` for having multiple application instances at the same time on the phone.

**Comment by zoontek** [comment]
@andrewkslv https://github.com/zoontek/react-native-bootsplash/pull/16 seems to fix the issue. I will make a new release with it today!

**Comment by shwanton** [comment]
Just tried that fork out and it works great! 
Much better solution than the one I proposed.
Thank you much!
