### ISSUE TITLE
Cannot generate assets ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by joshua-augustinus** [zoontek/react-native-bootsplash#180]
# Bug report

## Summary

Get an error trying to generate assets:
Run this in terminal:
```
npx react-native generate-bootsplash src/assets/splash/logo.png
```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:980:7)
    at generate (/Users/joshua/Documents/Development/git-driven/joshua_test_repo/node_modules/react-native-bootsplash/dist/commonjs/generate.js:108:35)
    at async Command.handleAction (/Users/joshua/Documents/Development/git-driven/joshua_test_repo/node_modules/@react-native-community/cli/build/cliEntry.js:160:7) {
  code: 'ERR_INVALID_ARG_TYPE'
```

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 4.34 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.6 => 0.60.6

```

Library version: 3.x.x

## Steps to reproduce

1. Create a react native project usine 0.60.x
2. Follow read me of this library

Describe what you expected to happen:

1. No errors.

## Reproducible sample code

clone this repo: https://github.com/joshua-augustinus/rn-training-bootsplash

```
yarn
npx react-native generate-bootsplash src/assets/splash/logo.png
```

You will get error.

**Comment by joshua-augustinus** [comment]
I'm able to generate assets fine using the older 2.2.8 instructions

**Comment by zoontek** [comment]
Thanks for the repo, it's very helpful.
I found the issue: RN `0.60` use a quite old version for `@react-native-community/cli` (`^2.6.0` vs `^4.10.0` for `0.63`)

I just added and tested the support, try `3.0.1`: https://github.com/zoontek/react-native-bootsplash/releases/tag/3.0.1
