### ISSUE TITLE
Release build crashes immediately but works fine in debug 

### ISSUE THREAD

**Issue by enestatli** [zoontek/react-native-bootsplash#200]
Hello, I wanted to replace my old splash screen with this package, it works really fine without a problem in debug mode. But when I release(using the `./gradlew bundleRelease` and for the APK `npx react-native run-android --variant=release`) the signed .apk and .aab(One of my app is already in the market)  crash instantly. 

The previous package that I used for the splash screen `react-native-splash-screen`, both my applications work fine with it but the last published for this package is like 2 years ago, so I  want to leave.

## Environment info

```
"react-native-bootsplash": "^3.1.2",
"react": "16.13.1",
"react-native": "0.63.2",
```

```
System:
    OS: Windows 8.1 6.3.9600
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
    Memory: 3.32 GB / 15.91 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
  Languages:
    Java: 1.8.0_211 - /c/Program Files/Java/jdk1.8.0_211/bin/javac
    Python: 3.9.1 - /c/Python39/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found
    
``` 

Here is the structure of  `res`  folder: 
<img src='https://i.imgur.com/bsYzawy.png' />

Here is the repo [https://github.com/enestatli/tdk-sozluk](https://github.com/enestatli/tdk-sozluk)

Thank you.

**Comment by zoontek** [comment]
@enestatli Hello. If you start the release build from Android Studio, what does the logcat say?

**Comment by enestatli** [comment]
Firstly, build with `./gradlew bundleRelease` for .aab. After that for .apk `npx react-native run-android --variant=release` both successfully build but crashes when open the app.

.aab log

```
BUILD SUCCESSFUL in 1m 17s
300 actionable tasks: 300 executed
```

.apk log

```BUILD SUCCESSFUL in 1m 9s
296 actionable tasks: 12 executed, 284 up-to-date
info Connecting to the development server...
info Starting the app on "emulator-5554"...
Starting: Intent { cmp=com.tdksozlukreactnative/.MainActivity }```

**Comment by zoontek** [comment]
Please paste logs from the crash

**Comment by enestatli** [comment]
@zoontek I just rebuild on Android Studio no crashes anymore, but I got this Warning `:app:bundleReleaseJsAndAssets`

I was getting this(warning) as an error when I built the app in the vscode console. That's weird.


<image src="https://i.imgur.com/AicMmqK.png" />

**Comment by zoontek** [comment]
This error does not seems related. It was probably the build cache. Did you clean the build artefacts after switching libraries?

**Comment by enestatli** [comment]
I did not, can you please tell me how could I ? Thanks.

**Comment by zoontek** [comment]
The easiest way is probably https://github.com/pmadruga/react-native-clean-project

Run `gradlew clean` for Android build artefacts only.

**Comment by enestatli** [comment]
Oh I already this many times `./gradlew clean` before build.

**Comment by enestatli** [comment]
After clean cache/reset, I build a new release and  here is  logcat says :

```
6:41.506 23673-23716/com.tdksozlukreactnative D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
2021-01-25 00:16:41.506 23673-23716/com.tdksozlukreactnative W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
2021-01-25 00:16:41.499 23673-23673/com.tdksozlukreactnative W/RenderThread: type=1400 audit(0.0:267): avc: denied { write } for name="property_service" dev="tmpfs" ino=7422 scontext=u:r:untrusted_app:s0:c159,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0 app=com.tdksozlukreactnative
2021-01-25 00:16:41.598 23673-23673/com.tdksozlukreactnative W/System.err: java.lang.ClassNotFoundException: com.tdksozlukreactnative.MainActivity
2021-01-25 00:16:41.600 23673-23673/com.tdksozlukreactnative W/System.err:     at java.lang.Class.classForName(Native Method)
2021-01-25 00:16:41.600 23673-23673/com.tdksozlukreactnative W/System.err:     at java.lang.Class.forName(Class.java:454)
2021-01-25 00:16:41.600 23673-23673/com.tdksozlukreactnative W/System.err:     at java.lang.Class.forName(Class.java:379)
2021-01-25 00:16:41.601 23673-23673/com.tdksozlukreactnative W/System.err:     at com.zoontek.rnbootsplash.RNBootSplashActivity.getMainActivityClass(RNBootSplashActivity.java:18)
2021-01-25 00:16:41.601 23673-23673/com.tdksozlukreactnative W/System.err:     at com.zoontek.rnbootsplash.RNBootSplashActivity.forwardIntentToMainActivity(RNBootSplashActivity.java:25)
2021-01-25 00:16:41.602 23673-23673/com.tdksozlukreactnative W/System.err:     at com.zoontek.rnbootsplash.RNBootSplashActivity.onCreate(RNBootSplashActivity.java:47)
2021-01-25 00:16:41.602 23673-23673/com.tdksozlukreactnative W/System.err:     at android.app.Activity.performCreate(Activity.java:7802)
2021-01-25 00:16:41.603 23673-23673/com.tdksozlukreactnative W/System.err:     at android.app.Activity.performCreate(Activity.java:7791)
2021-01-25 00:16:41.604 23673-23673/com.tdksozlukreactnative W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
2021-01-25 00:16:41.605 23673-23673/com.tdksozlukreactnative W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
2021-01-25 00:16:41.605 23673-23673/com.tdksozlukreactnative W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
2021-01-25 00:16:41.606 23673-23673/com.tdksozlukreactnative W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
2021-01-25 00:16:41.607 23673-23673/com.tdksozlukreactnative W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2021-01-25 00:16:41.608 23673-23673/com.tdksozlukreactnative W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2021-01-25 00:16:41.608 23673-23673/com.tdksozlukreactnative W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
2021-01-25 00:16:41.609 23673-23673/com.tdksozlukreactnative W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2021-01-25 00:16:41.609 23673-23673/com.tdksozlukreactnative W/System.err:     at android.os.Looper.loop(Looper.java:214)
2021-01-25 00:16:41.610 23673-23673/com.tdksozlukreactnative W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
2021-01-25 00:16:41.611 23673-23673/com.tdksozlukreactnative W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-01-25 00:16:41.611 23673-23673/com.tdksozlukreactnative W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2021-01-25 00:16:41.612 23673-23673/com.tdksozlukreactnative W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-01-25 00:16:41.613 23673-23673/com.tdksozlukreactnative W/System.err: Caused by: java.lang.ClassNotFoundException: com.tdksozlukreactnative.MainActivity
```

**Comment by zoontek** [comment]
Does `com/tdksozlukreactnative/MainActivity.java` exists?

**Comment by enestatli** [comment]
Thanks for reopening the issue. Yes, it exists. 

``` 
package com.tdksozlukreactnative;

import android.os.Bundle; 

import com.facebook.react.ReactActivity;
import com.zoontek.rnbootsplash.RNBootSplash;

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "tdkSozluk";
  }

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
  }
}
```

**Comment by enestatli** [comment]
So it turns out the problem happens because of the wrong folder name located in `java\com\......` I did not realize.

Solved the problem by renaming the `tdksozluk` to `tdksozlukreactnative`
