### ISSUE TITLE
Error Option "--flavor" is missing.

### ISSUE THREAD

**Issue by shockwave13** [zoontek/react-native-bootsplash#231]
# Bug report

Hi. I'm getting an error 'Error Option "--flavor" is missing.' when i run command for Assets generation.
So i don't know what the problem is. Maybe i'm doing something wrong.

      
## Environment info

System:
    OS: macOS 10.15.7
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.9.0 - ~/Documents/Work/Projects/PreOp/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 3.2.1

## Steps to reproduce

- npm install --save react-native-bootsplash
- cd ios && pod install && cs..
- npx react-native generate-bootsplash assets/bootsplash_logo_original.png \ --background-color=F5FCFF \ --logo-width=100 \ --assets-path=assets \ --flavor=main

## Reproducible sample code

`error Option "--flavor" is missing. Run CLI with --verbose flag for more details.
      Error: Option "--flavor" is missing
          at /Users/aldoraine/Documents/Work/Projects/PreOp/node_modules/@react-native-community/cli/build/tools/assertRequiredOptions.js:51:13
          at Array.forEach (<anonymous>)
          at assertRequiredOptions (/Users/aldoraine/Documents/Work/Projects/PreOp/node_modules/@react-native-community/cli/build/tools/assertRequiredOptions.js:40:11)
          at Command.handleAction (/Users/aldoraine/Documents/Work/Projects/PreOp/node_modules/@react-native-community/cli/build/index.js:181:42)
          at Command.listener (/Users/aldoraine/Documents/Work/Projects/PreOp/node_modules/commander/index.js:315:8)
          at Command.emit (node:events:378:20)
          at Command.parseArgs (/Users/aldoraine/Documents/Work/Projects/PreOp/node_modules/commander/index.js:651:12)
          at Command.parse (/Users/aldoraine/Documents/Work/Projects/PreOp/node_modules/commander/index.js:474:21)
          at setupAndRun (/Users/aldoraine/Documents/Work/Projects/PreOp/node_modules/@react-native-community/cli/build/index.js:267:24)
          at run (/Users/aldoraine/Documents/Work/Projects/PreOp/node_modules/@react-native-community/cli/build/index.js:206:11)
      npm ERR! code 1
      npm ERR! path /Users/aldoraine/Documents/Work/Projects/PreOp
      npm ERR! command failed
      npm ERR! command sh -c react-native "generate-bootsplash" "assets/bootsplash_logo_original.png" " --background-color=F5FCFF" " --logo-width=100" " --assets-path=assets" " --flavor=main"
      
      npm ERR! A complete log of this run can be found in:
      npm ERR!     /Users/aldoraine/.npm/_logs/2021-04-30T08_57_31_121Z-debug.log`

**Comment by zoontek** [comment]
@shockwave13 Try with the latest version: https://github.com/zoontek/react-native-bootsplash/releases/tag/3.2.2
