### ISSUE TITLE
v4.0.2 Android 31 - Dev menu doesn't open in debug

### ISSUE THREAD

**Issue by fr0staman** [zoontek/react-native-bootsplash#296]
### Bug summary

After installing debug apk on phone, I have no method to open dev menu, and seeing progress of bundling/downloading.

Seems in emulator, and my phone (POCO X3).
![image](https://user-images.githubusercontent.com/77665176/147417084-bbdb5fed-5924-4bae-b92f-c2e30773a6e3.png)

### Library version

4.0.2

### Environment info

```shell
OS: Windows 10 10.0.19042
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 1.04 GB / 15.37 GB
  Binaries:
    Node: 16.13.0 - C:\Temp\xfs-59b23a57\node.CMD
    Yarn: 3.1.0 - C:\Temp\xfs-59b23a57\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: Version     2020.3.0.0 AI-203.7717.56.2031.7784292
    Visual Studio: 16.10.31321.278 (Visual Studio Community�2019)
  Languages:
    Java: 1.8.0_302
  npmPackages:
    @react-native-community/cli: ^6.3.1 => 6.3.1
    react: ^17.0.2 => 17.0.2
    react-native: ^0.66.4 => 0.66.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. .\gradlew assembleDebug
2. Install apk on phone
3. Try open dev menu.

### Reproducible sample code

```js
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <item name="android:statusBarColor">@android:color/transparent</item>
    </style>
    <style name="BootTheme" parent="Theme.SplashScreen">
        <item name="windowSplashScreenBackground">@color/bootsplash_background</item>
        <item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>
        <item name="postSplashScreenTheme">@style/AppTheme</item>

        <item name="android:windowLightStatusBar">true</item>
        <item name="android:windowLightNavigationBar">true</item>
    </style>
</resources>
```

**Comment by zoontek** [comment]
You mean when the splash screen is active / visible? Or once the app has loaded?

**Comment by fr0staman** [comment]
> You mean when the splash screen is active / visible? Or once the app has loaded?

When app in debug loads splash screen.
Anywhere, if app loads splash screen and don't hide him manually, or app is not loaded (but splash screen is active),

My problematic is this:
When I want the first start of debug app in phone, and his don't know about IP-address of my metro (external phone, yeah) - I can't open debug menu, and choose IP-address of my metro bundler.
And I cant see errors when splash screen is active (example: problems with AppRegistry).

**Comment by zoontek** [comment]
That's complex, since the splash screen is above the React `RootView`.
Download progress is visible in Metro CLI, but Android react native helpers doesn't offer an equivalent to iOS  `RCTJavaScriptDidFailToLoadNotification` (as I know) to hide the splash screen if the download failed.

I would recommend wrapping the native init function in a condition, like:

```java
if (!BuildConfig.DEBUG) {
  RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
}
```

**Comment by fr0staman** [comment]
> That's complex, since the splash screen is above the React `RootView`. Download progress is visible in Metro CLI, but Android react native helpers doesn't offer an equivalent to iOS `RCTJavaScriptDidFailToLoadNotification` (as I know) to hide the splash screen if the download failed.
> 
> I would recommend wrapping the native init function in a condition, like:
> 
> ```java
> if (!BuildConfig.DEBUG) {
>   RNBootSplash.init(R.drawable.bootsplash, MainActivity.this);
> }
> ```

I wrapped native init function as you did, but it causes crash in Debug
Error by logcat:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.abillslite/com.abillslite.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
       at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
       at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
       at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:687)
       at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:201)
       at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:92)
       at com.abillslite.MainActivity$1.loadApp(MainActivity.java:28)
       at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:86)
       at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
       at android.app.Activity.performCreate(Activity.java:7994)
       at android.app.Activity.performCreate(Activity.java:7978)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
       ... 11 more
```
       
Hence, release - don't crash and works fine.
Maybe, I don't understand something :)

**Comment by zoontek** [comment]
Assets must be scoped to release too.
Keep `styles.xml` and `AndroidManifest.xml` untouched, overrides them in `android/app/src/release`.

More infos: https://developer.android.com/studio/build/build-variants#sourcesets

**Comment by xxsnakerxx** [comment]
```
adb reverse tcp:8081 tcp:8081
```

and re-run

**Comment by maximilize** [comment]
> ```
> adb reverse tcp:8081 tcp:8081
> ```
> 
> and re-run

This only if you have ADB access to the device, that's not always the case.

**Comment by maximilize** [comment]
All right, here comes a clean solution, maybe it's worth adding it to the README, else this lib negatively affects the dev experience with RN.

1. As @zoontek mentioned, change the code in `MainActivity.java`:

```java
        if (!BuildConfig.DEBUG) {
          RNBootSplash.init(getPlainActivity()); // <- initialize the splash screen
        }
```

2. Edit `android/app/src/debug/AndroidManifest.xml` and add the `theme` related props to the `application` tag:

```java
    <application
        android:usesCleartextTraffic="true"
        tools:targetApi="28"
        tools:ignore="GoogleAppIndexingWarning"
        tools:replace="android:theme"
        android:theme="@style/AppTheme">
```
