### ISSUE TITLE
You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by dancomanlive** [zoontek/react-native-bootsplash#323]
### Bug summary

`2022-02-16 20:35:22.974 18946-18946/com.nytimes E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nytimes, PID: 18946
    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:846)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:809)
        at androidx.appcompat.app.AppCompatDelegateImpl.onPostCreate(AppCompatDelegateImpl.java:530)
        at androidx.appcompat.app.AppCompatActivity.onPostCreate(AppCompatActivity.java:151)
        at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1383)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3899)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
`

### Library version

"^4.1.3"

### Environment info

```shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 144.34 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. clone https://github.com/dancomanlive/nytimes-react-native/tree/feature/react-native-bootsplash
2. yarn
3. yarn run android
4. see LogCat

### Reproducible sample code

```js
https://github.com/dancomanlive/nytimes-react-native/tree/feature/react-native-bootsplash
```

**Comment by zoontek** [comment]
@dancomanlive You deleted `getMainComponentName` from your `MainActivity`.

Add it back, it works.

```diff
package com.nytimes;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.zoontek.rnbootsplash.RNBootSplash;

public class MainActivity extends ReactActivity {

+ /**
+  * Returns the name of the main component registered from JavaScript. This is used to schedule
+  * rendering of the component.
+  */
+ @Override
+ protected String getMainComponentName() {
+   return "NYTimes";
+ }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {

      @Override
      protected void loadApp(String appKey) {
        RNBootSplash.init(MainActivity.this); // <- initialize the splash screen
        super.loadApp(appKey);
      }
    };
  }
}
```
