### ISSUE TITLE
Error when generating in rn 0.69

### ISSUE THREAD

**Issue by Pkcarreno** [zoontek/react-native-bootsplash#362]
### Bug summary

testing in a new project, the command to generate jumps error generating ios elements, this was tested on windows and mac

```bash

npx react-native generate-bootsplash ./assets/logo.png --background-color=F8FAFD

    Android
✏️   android\app\src\main\res\values\colors.xml
✨  android\app\src\main\res\mipmap-hdpi\bootsplash_logo.png (432x432)
✨  android\app\src\main\res\mipmap-xhdpi\bootsplash_logo.png (576x576)
✨  android\app\src\main\res\mipmap-mdpi\bootsplash_logo.png (288x288)
✨  android\app\src\main\res\mipmap-xxhdpi\bootsplash_logo.png (864x864)
✨  android\app\src\main\res\mipmap-xxxhdpi\bootsplash_logo.png (1152x1152)

    iOS
TypeError: Cannot read properties of undefined (reading 'replace')
    at generate (D:\pedro\Developer\testApp\node_modules\react-native-bootsplash\dist\commonjs\generate.js:252:41)
    at async Command.handleAction (D:\pedro\Developer\testApp\node_modules\@react-native-community\cli\build\index.js:192:9)

```

### Library version

4.1.6

### Environment info

```shell
npx react-native info
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
    Memory: 4.74 GB / 11.85 GB
  Binaries:
    Node: 16.15.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 8.5.5 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 30.0.2, 30.0.3, 31.0.0
      System Images: android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.14 - C:\Program Files\Microsoft\jdk-11.0.14.9-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.0 => 0.69.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. generate new react-native project with `npx react-native init testApp`
2. install `react-native-bootsplash` and then generate bootsplash

### Reproducible sample code

```js
as I said, you just have to generate a new project and install `react-native-bootsplash` and generate
```

**Comment by zoontek** [comment]
Nevermind, I pushed a new version: https://github.com/zoontek/react-native-bootsplash/releases/tag/4.2.0
