### ISSUE TITLE
Crash for Android API level 32 -> Solution to be added to the readme/migration file

### ISSUE THREAD

**Issue by CrisPRuz** [zoontek/react-native-bootsplash#368]
### Bug summary

For Android devices using API level +31, you can get the following error:

```
FATAL EXCEPTION: pool-12-thread-1
Process: com.heytrade.wealth.beta, PID: 12699
java.lang.IllegalArgumentException: com.heytrade.wealth.beta: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

### Library version

4.2.3

### Environment info

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 56.75 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/cparedes/.gem/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-26 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-32 | Google APIs Intel x86 Atom_64
      Android NDK: 20.1.5948944
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Load a project with RN project under `compileSdkVersion = 31 `and `targetSdkVersion = 31`

### Reproducible sample code

I can't provide code for this as it was discovered in a non open source/personal project but I've found a workaround for this here:

https://stackoverflow.com/questions/70894168/targeting-s-version-31-and-above-requires-that-one-of-flag-immutable-or-flag

In my case, I solved it by adding this to file `android/app/build.gradle`: 

```
dependencies {
  // ...
  implementation 'androidx.work:work-runtime:2.7.1'
}
```

**Comment by zoontek** [comment]
@CrisPRuz This does not seems related to this library. It doesn't use `PendingIntent` or `androidx.work:work-runtime` at all. Could be related to another one (this lib only target SDK 31 but doesn't trigger this directly)

**Comment by zoontek** [comment]
@CrisPRuz I'm not sure a _Troubleshooting_ would help since the issue is not triggered by the library itself.
Maybe just keeping this issue searchable is enough, since React Native 0.68+ already [require SDK 31+](https://github.com/facebook/react-native/blob/0.68-stable/template/android/build.gradle)

**Comment by CrisPRuz** [comment]
I close the issue then!
