### ISSUE TITLE
Cant generate bootsplash

### ISSUE THREAD

**Issue by kaaax0815** [zoontek/react-native-bootsplash#377]
### Bug summary

If i run `yarn react-native generate-bootsplash c:\Users\Bernd\Pictures\Photoshop\SmartAlarmClock.png --background-color 00021f` i get an error message:
```error Cannot read properties of null (reading 'xcodeProject').
TypeError: Cannot read properties of null (reading 'xcodeProject')
    at Object.func (C:\Users\Bernd\Documents\Programmieren\Typescript\smart-alarm-clock\app\node_modules\react-native-bootsplash\react-native.config.js:60:31)
    at Command.handleAction (C:\Users\Bernd\Documents\Programmieren\Typescript\smart-alarm-clock\app\node_modules\@react-native-community\cli\build\index.js:192:23)
    at Command.listener (C:\Users\Bernd\Documents\Programmieren\Typescript\smart-alarm-clock\app\node_modules\commander\index.js:315:8)
    at Command.emit (node:events:527:28)
    at Command.parseArgs (C:\Users\Bernd\Documents\Programmieren\Typescript\smart-alarm-clock\app\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\Bernd\Documents\Programmieren\Typescript\smart-alarm-clock\app\node_modules\commander\index.js:474:21)
    at setupAndRun (C:\Users\Bernd\Documents\Programmieren\Typescript\smart-alarm-clock\app\node_modules\@react-native-community\cli\build\index.js:271:24)
    at Object.run (C:\Users\Bernd\Documents\Programmieren\Typescript\smart-alarm-clock\app\node_modules\@react-native-community\cli\build\index.js:212:11)
    at Object.<anonymous> (C:\Users\Bernd\Documents\Programmieren\Typescript\smart-alarm-clock\app\node_modules\react-native\cli.js:16:7)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

I think this issue occurs because I deleted the ios folder (because I dont need it) and thus it cant find a xcode project 

### Library version

4.2.3

### Environment info

```shell
OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
    Memory: 1.07 GB / 7.43 GB
  Binaries:
    Node: 16.15.1 - ~\AppData\Local\Temp\yarn--1659911879534-0.8531473718856586\node.CMD
    Yarn: 1.22.19 - ~\AppData\Local\Temp\yarn--1659911879534-0.8531473718856586\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
  IDEs:
    Android Studio: AI-212.5712.43.2112.8609683
    Visual Studio: Not Found
  Languages:
    Java: 11.0.12 - C:\Program Files\Android\Android Studio\jre\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.3 => 0.69.3
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Clone [smart-alarm-clock](https://github.com/kaaax0815/smart-alarm-clock/tree/f2d32951ef5ef36f6ca820e699d6d6d4ed13ac33)
2. Run `yarn add react-native-bootsplash`
3. Run `yarn react-native generate-bootsplash c:\Users\Bernd\Pictures\Photoshop\SmartAlarmClock.png --background-color 00021f`

### Reproducible sample code

```js
Not needed
```

**Comment by zoontek** [comment]
@kaaax0815 Fix is shipped: https://github.com/zoontek/react-native-bootsplash/releases/tag/4.2.4
