### ISSUE TITLE
`view.setBackgroundResource(drawableResId)` cause oom on android with large image

### ISSUE THREAD

**Issue by KingAmo** [zoontek/react-native-bootsplash#38]
i have a `132KB` png image as splash screen, and app crash on launch with the following error message:
```
   java.lang.OutOfMemoryError: Failed to allocate a 144072012 byte allocation with 2234122 free bytes and 92MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
        at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:467)
        at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:497)
        at android.graphics.drawable.BitmapDrawable.updateStateFromTypedArray(BitmapDrawable.java:762)
        at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:724)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
        at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:254)
        at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:164)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
        at android.content.res.Resources.loadDrawableForCookie(Resources.java:2630)
        at android.content.res.Resources.loadDrawable(Resources.java:2540)
        at android.content.res.Resources.getDrawable(Resources.java:806)
        at android.content.Context.getDrawable(Context.java:458)
        at android.view.View.setBackgroundResource(View.java:17202)
        at com.zoontek.rnbootsplash.RNBootSplash$1.run(RNBootSplash.java:25)
        at android.app.Activity.runOnUiThread(Activity.java:5511)
        at com.zoontek.rnbootsplash.RNBootSplash.show(RNBootSplash.java:17)
        at com.kjkdoctor.MainActivity.onCreate(MainActivity.java:49)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
source code error line:

https://github.com/zoontek/react-native-bootsplash/blob/38c81194993fbdf78eda356d7f9e1c4b030c7b61/android/src/main/java/com/zoontek/rnbootsplash/RNBootSplash.java#L25

### 💻 My environment
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 22.91 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.15.0 - /usr/local/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 28.0.3, 29.0.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```
- react-native-bootsplash version: `1.0.3`
- OS version: `android 6.0`
- Simulator: yes 

### 🕵️‍♂️ Reproducing the issue

Explain what you did, what you expected to happen, and what actually happens.
Provide some code or screenshots if needed.

### 🤞Solution
temporary solution: 
https://stackoverflow.com/questions/14096061/android-setbackgroundresource-cause-out-of-memory-excepiton

**Comment by KingAmo** [comment]
it seems that it is better use `setBackgroundDrawable`

**Comment by zoontek** [comment]
@KingAmo `setBackgroundDrawable` is deprecated.
Could you provide a screenshot of your `res` directory organization (all subfolders opened)? That's not normal that you provoke an `OutOfMemoryError` error with only a 144kb image.

**Comment by KingAmo** [comment]
![image](https://user-images.githubusercontent.com/29938227/70859012-86078400-1f47-11ea-8f40-7d12ca32eec2.png)
@zoontek  here it is, I think nothing special

**Comment by KingAmo** [comment]
this is  my `bootsplash.xml`
```
<?xml version="1.0" encoding="utf-8"?>

<layer-list xmlns:android="http://schemas.android.com/apk/res/android" android:opacity="opaque">
    <!-- the background color. it can be a system color or a custom one defined in colors.xml -->
    <item android:drawable="@android:color/white" />

    <item>
        <!-- the app logo, centered horizontally and vertically -->
<!--        <bitmap android:src="@mipmap/ic_launcher" />-->
        <bitmap
            android:src="@drawable/launch_screen"
            android:tileMode="disabled"
            android:filter="true" />
    </item>
</layer-list>
```

**Comment by zoontek** [comment]
@KingAmo You have to provide resized drawable resources in each mipmap-x directory to prevent dynamic resizing at runtime and the OOM.

See the accepted from the StackOverflow linked you posted.

**Comment by KingAmo** [comment]
i see, thanks a lot
