### ISSUE TITLE
Android crashes on first launch

### ISSUE THREAD

**Issue by k0rn4l** [zoontek/react-native-bootsplash#387]
### Bug summary

Hi! 

After installing the app, it fails to open at fist. Second launch show the splash screen. 

Tested on device with signed apk, on Android 11:

<details>
  <summary>LogCat</summary>
  
```--------- beginning of crash
09-08 18:12:23.089  6679  6679 E AndroidRuntime: FATAL EXCEPTION: main
09-08 18:12:23.089  6679  6679 E AndroidRuntime: Process: com.test.app, PID: 6679
09-08 18:12:23.089  6679  6679 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.app/com.test.app.MainActivity}: android.view.InflateException: Binary XML file line #24 in com.test.app:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f03021a a=-1}
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #24 in com.test.app:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f03021a a=-1}
09-08 18:12:23.089  6679  6679 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f03021a a=-1}
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:826)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8231)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8429)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:452)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:380)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:58)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.view.View.inflate(View.java:26707)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl$_splashScreenView$2.invoke(SplashScreenViewProvider.kt:94)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl$_splashScreenView$2.invoke(SplashScreenViewProvider.kt:93)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl.get_splashScreenView(SplashScreenViewProvider.kt:93)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl.createSplashScreenView(SplashScreenViewProvider.kt:103)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at androidx.core.splashscreen.SplashScreenViewProvider.<init>(SplashScreenViewProvider.kt:52)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at androidx.core.splashscreen.SplashScreen$Impl.setOnExitAnimationListener(SplashScreen.kt:305)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at androidx.core.splashscreen.SplashScreen.setOnExitAnimationListener(SplashScreen.kt:185)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at com.zoontek.rnbootsplash.RNBootSplashModule.init(RNBootSplashModule.java:75)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at com.zoontek.rnbootsplash.RNBootSplash.init(RNBootSplash.java:10)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at com.test.app.MainActivity.onCreate(MainActivity.java:14)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7994)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7978)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-08 18:12:23.089  6679  6679 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
09-08 18:12:23.098   506  6770 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
09-08 18:12:23.098   506  4554 W ActivityTaskManager:   Force finishing activity com.test.app/.MainActivity
``` 
  

</details>

Sometimes it just hangs, and after a while: 

`09-19 10:58:38.526   506   533 I ActivityTaskManager: Displayed com.test.app.MainActivity: +41s397ms`

</details>

### Library version

4.3.2

### Environment info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 91.84 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/kbs-mac/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.0 => 0.70.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. init new react native project
2. install bootsplash
3. run on emulator with api level 30

### Reproducible sample code

```js
-
```

**Comment by zoontek** [comment]
Delete that: `layout/splash_screen_view`

**Comment by k0rn4l** [comment]
From where? No layout is declared in my android project. Sorry, not a native dev.

The only reference to a splash_screen_view are in node_modules, and only after a build.

**Comment by zoontek** [comment]
@k0rn4l Didn't you installed another libs before? (from expo, for example)

**Comment by k0rn4l** [comment]
So I started a fresh project, then started installing the libs we use, and then import our src files. BootSplash was one the firsts t be installed, because when I started to update our existing project, this error came along. But it looks like it persists.

**Comment by jpudysz** [comment]
I had the same issue, and I've never used an expo.
Follow the installation steps for Android once again, especially `MainActivity.java` and `styles.xml` steps.

**Comment by k0rn4l** [comment]
After many reinstalls, and moving the function around in MainActivity.java, it seems the errors has went away
