### ISSUE TITLE
App Crashes on Launch after migrating.

### ISSUE THREAD

**Issue by ThukuWakogi** [zoontek/react-native-bootsplash#398]
### Bug summary

I am upgrading my react native app from v0.63.0 to v0.70.4. As a result, I am also migrating react-native-bootsplash from v3 to v4. Starting the application crushes and inspecting the app with android studio produces the following error:
```
2022-10-26 16:30:05.216 1257-1257/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 1257
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.myapp.MainActivity}: android.view.InflateException: Binary XML file line #24 in com.myapp:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f030210 a=-1}
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3432)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: android.view.InflateException: Binary XML file line #24 in com.myapp:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f030210 a=-1}
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f030210 a=-1}
        at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:826)
        at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8231)
        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8429)
        at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:452)
        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:380)
        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:58)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
        at android.view.View.inflate(View.java:26711)
        at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl$_splashScreenView$2.invoke(SplashScreenViewProvider.kt:94)
        at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl$_splashScreenView$2.invoke(SplashScreenViewProvider.kt:93)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl.get_splashScreenView(SplashScreenViewProvider.kt:93)
        at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl.createSplashScreenView(SplashScreenViewProvider.kt:103)
        at androidx.core.splashscreen.SplashScreenViewProvider.<init>(SplashScreenViewProvider.kt:52)
        at androidx.core.splashscreen.SplashScreen$Impl.setOnExitAnimationListener(SplashScreen.kt:305)
        at androidx.core.splashscreen.SplashScreen.setOnExitAnimationListener(SplashScreen.kt:185)
        at com.zoontek.rnbootsplash.RNBootSplashModule.init(RNBootSplashModule.java:75)
        at com.zoontek.rnbootsplash.RNBootSplash.init(RNBootSplash.java:10)
        at com.myapp.MainActivity.onCreate(MainActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:8191)
        at android.app.Activity.performCreate(Activity.java:8175)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3405)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3596)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2022-10-26 16:30:05.216 1257-1257/? E/AndroidRuntime:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

### Library version

4.3.2

### Environment info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.00 GB / 7.89 GB
  Binaries:
    Node: 16.17.1 - ~\AppData\Local\Temp\yarn--1666793081375-0.5510236036397524\node.CMD
    Yarn: 1.22.19 - ~\AppData\Local\Temp\yarn--1666793081375-0.5510236036397524\yarn.CMD
    npm: 8.15.0 - D:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.3.32811.315 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.16.1 - C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.4 => 0.70.4
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Migrate bootsplash from v3 to v4

### Reproducible sample code

```js
-
```

**Comment by zoontek** [comment]
@ThukuWakogi Hi! Check that it happens on a fresh project instead. Issues are to declare actual issue with the library, here it just seems to be a migration issue.

Check that you correctly followed https://github.com/zoontek/react-native-bootsplash/blob/master/MIGRATION.md#migration-from-v3

Check that your RN migration is correct using https://react-native-community.github.io/upgrade-helper/
