### ISSUE TITLE
[Android 12] App crashes on launch

### ISSUE THREAD

**Issue by adrianso** [zoontek/react-native-bootsplash#409]
## Description
App crashes on launch in Android 12 emulator, but works fine in Android 13 emulator and iOS.
Possibly related to #398 and #387

## Libraries
`react-native`: 0.70.6
`react-native-bootsplash`: 4.3.3

## Stack trace
```
FATAL EXCEPTION: main

Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0403d4 a=-1}

FATAL EXCEPTION: main
Process: nz.co.newworld.clubcard.dev, PID: 8126
java.lang.RuntimeException: Unable to start activity ComponentInfo{nz.co.newworld.clubcard.dev/nz.co.newworld.clubcard.MainActivity}: android.view.InflateException: Binary XML file line #24 in nz.co.newworld.clubcard.dev:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f0403d4 a=-1}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3533)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3690)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:99)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2138)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7858)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)```

### Library version

4.3.3

### Environment info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 102.95 MB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/98296_1669844938756/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/98296_1669844938756/bin/npm
    Watchman: 2022.11.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/adrian/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

1. Create new react-native project from scratch
1. Add `react-native-bootsplash`
1. `yarn android` in Android 12 emulator
1. App crashes

### Reproducible sample code

```js
Minimal runnable repo
https://github.com/adrianso/bootsplash-android12-crash
```

**Comment by adrianso** [comment]
@zoontek Yes, I have checked #394, but in this case, that fix didn't apply to me. There is only 1 `android:theme` at the application level. You can see the [manifest here](https://github.com/adrianso/bootsplash-android12-crash/blob/main/android/app/src/main/AndroidManifest.xml).

The [reproducible repo](https://github.com/adrianso/bootsplash-android12-crash) is a brand new React Native installation with nothing but react-native-bootsplash set up. I have also followed the set up instructions to the dot.

**Comment by zoontek** [comment]
No crash on my side. Maybe you just forgot to do a Gradle Sync after adding AndroidX core splashscreen? Do it, a gradle clean and rebuild, it should be fine.

https://user-images.githubusercontent.com/1902323/205284169-829dba27-8e59-4a8a-a143-703bb8de9a66.mp4

**Comment by rkz98** [comment]
For me, working on emulator but not on real device.

**Comment by raymondjacobson** [comment]
Same, real device android 12 immediately crashes. Samsung s10.

**Comment by zoontek** [comment]
I tried on both, never had an issue, even with different real devices. Guess you might miss something.

**Comment by adrianso** [comment]
@zoontek Thanks for the spending the time to look into this. I had a look at the video that you created and noticed that the biggest difference is that you are running the project from Android Studio, whereas I am running it from the CLI.

I tried doing the same, and surprise surprise, it worked! Thanks!

The difference boils down to the fact that Android Studio would run `gradle sync` automatically when you open the project. This is surprising because the gradle sync step was never mentioned in any React Native or bootsplash docs. There are well over 100 dependencies in my project, and this is the first time I have to do this. Just for my education, what does `gradle sync` do, and what makes react-native-bootsplash` different to all the other React Native dependencies?

**Comment by zoontek** [comment]
@adrianso I mentioned it actually:

> Maybe you just forgot to do a Gradle Sync after adding AndroidX core splashscreen?

Gradle sync is basically an equivalent of `yarn install` / `pod install`.

Even if `react-native-bootsplash` is autolinked, `androidx.core:core-splashscreen:1.0.0` is added to your `build.gradle` and need to be downloaded and installed (it cannot be added as a dependency of this package since you have to access `Theme.SplashScreen` from your codebase)

I never though people would struggle with this. I will add a note in the README.

**Comment by zoontek** [comment]
@adrianso I added a small warning in the README:

<img width="1057" alt="Screenshot 2022-12-04 at 02 50 16" src="https://user-images.githubusercontent.com/1902323/205470083-2341019b-1a58-4a4d-9c7c-dab077962342.png">

**Comment by adrianso** [comment]
@zoontek Thanks for responding back so fast! 

I have applied the fix you suggested, and have been testing it on different devices the whole afternoon.

<img width="755" alt="Screenshot 2022-12-04 at 10 09 12 PM" src="https://user-images.githubusercontent.com/836310/205482995-bb94079c-7b4e-4825-a097-44d5a5369248.png">

What I have tested:
- API 33 (33) - OK
- S (31) - OK
- S (S) - Crash on launch
- R (30) - OK

You can only see this Android version if you selected a relatively old phone model, e.g. the Pixel 4.

**Comment by zoontek** [comment]
Be sure that you are using item names like

`<item name="windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>`

and not

`<item name="android:windowSplashScreenAnimatedIcon">@mipmap/bootsplash_logo</item>`

Using the `android:` prefixed names would means that you are not using the AndroidX polyfill on Android < 12.

**Comment by adrianso** [comment]
@zoontek This is what the [styles.xml](https://github.com/adrianso/bootsplash-android12-crash/blob/main/android/app/src/main/res/values/styles.xml) looks like in the reproducible repo. No `android:` in the `name` atrribute.

Bootsplash also works fine on Android 9, 10 and 11, just not that specific version of Android S highlighted in the screenshot.

Here is the stack trace requested.
```
FATAL EXCEPTION: main
Process: com.rnscratch, PID: 8646
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rnscratch/com.rnscratch.MainActivity}: android.view.InflateException: Binary XML file line #24 in com.rnscratch:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f030103 a=-1}
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3552)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3709)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:100)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2151)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7695)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
Caused by: android.view.InflateException: Binary XML file line #24 in com.rnscratch:layout/splash_screen_view: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f030103 a=-1}
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f030103 a=-1}
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:827)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:8221)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8419)
	at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:452)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:380)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:58)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1125)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
	at android.view.View.inflate(View.java:26956)
	at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl$_splashScreenView$2.invoke(SplashScreenViewProvider.kt:94)
	at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl$_splashScreenView$2.invoke(SplashScreenViewProvider.kt:93)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl.get_splashScreenView(SplashScreenViewProvider.kt:93)
	at androidx.core.splashscreen.SplashScreenViewProvider$ViewImpl.createSplashScreenView(SplashScreenViewProvider.kt:103)
	at androidx.core.splashscreen.SplashScreenViewProvider.<init>(SplashScreenViewProvider.kt:52)
	at androidx.core.splashscreen.SplashScreen$Impl.setOnExitAnimationListener(SplashScreen.kt:305)
	at androidx.core.splashscreen.SplashScreen.setOnExitAnimationListener(SplashScreen.kt:185)
	at com.zoontek.rnbootsplash.RNBootSplashModule.init(RNBootSplashModule.java:75)
	at com.zoontek.rnbootsplash.RNBootSplash.init(RNBootSplash.java:10)
	at com.rnscratch.MainActivity.onCreate(MainActivity.java:52)
	at android.app.Activity.performCreate(Activity.java:7959)
	at android.app.Activity.performCreate(Activity.java:7939)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3525)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3709)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:100)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2151)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7695)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

**Comment by zoontek** [comment]
@adrianso Did you clean your project, did a gradle sync and built it for this target using Android Studio? Because this just don't make sense (it just cannot locate the splash screen layout file)

**Comment by adrianso** [comment]
@zoontek I figured it out. Turned out that the version of Android I am using is SPP3.210325.010, which is the Developer Preview 3 build of Android 12. Since this is not a consumer facing version of Android, we can safely ignore this crash.

Thanks for your help!

**Comment by zoontek** [comment]
@adrianso I'm glad we solved it. Thanks for the sponsorship! 🙂
