### ISSUE TITLE
After Splash Screen remains blank screen (Android)

### ISSUE THREAD

**Issue by SocDario** [zoontek/react-native-bootsplash#456]
### Bug summary

Hello,
First of all great lib, good job and thanks a lot for contributing to the community.

I have followed all the steps in documentation for Android and it was working fine on Android 13 (Samsung galaxy s21), but when app was released people was reporting that on first download of the app and starting it from google play store they were expiriencing blank black screen after splash screen, but after they close app and reopen it works fine. This isn't probably bug in the lib, but just want to check if someone had same issue and is there a way to solve it?

It happens on differend android versions and phones, some of them are under android 12 version but there were also issues with 12+ devices.

### Library version

v4.7.1

### Environment info

```shell
System:
Linux 5.19 Ubuntu 22.04.2 LTS
x64 AMD Ryzen 5 3600 6-core
13/15.57 GB
Shell: 5.1.16

Binaries:
 Node: 18.14.2
 npm: 9.5.0

npmPac:
 React: 18.1.0
 React-native: 0.70.1

minSdkVersion: 23
compileSdkVersion = 33
targetSdkVersion = 33
kotlin_version = 1.6.21
```

### Steps to reproduce

Blank screen after splash screen:
1. Download App from play store
2. Open it from play store

Working example:
1. Close app opened from google play store
2. Reopen it clicking on app icon from dashboard

### Reproducible sample code

```js
If needed I can provide example of lib implementation, but I followed steps from docs.
```

**Comment by zoontek** [comment]
Hello! I never heard of that, could you provide a repository with the setup on Android? (copy / paste how you setted it up in your project)

**Comment by SocDario** [comment]
Yeah I was thinking the same, app was build and tested mainly on Android 13 real device, and on few android emulators from android 10 to 13. 
I will try to provide repo with android folder as soon as I can, thanks for quick response!

**Comment by zoontek** [comment]
I'm currently working on a new version without AndroidX core splashscreen package and it kind of fixes this issue

**Comment by SocDario** [comment]
Great to hear that! I will close this issue until new version is available then, do you know maybe at least month of the release?

**Comment by zoontek** [comment]
Probably before the end of June 🙂

**Comment by nhutph** [comment]
any update for issue bro ?

**Comment by zoontek** [comment]
@nhutph I had other plans, visibly.

**Comment by jacobjones123** [comment]
Hello 👋  Any update on removing AndroidX?

**Comment by zoontek** [comment]
@jacobjones123 I've got it fully working, as I work during the week I will probably be able to publish the first this weekend 🙂

**Comment by jacobjones123** [comment]
awesome 😄 Thanks for the update @zoontek

**Comment by anuj1357** [comment]
@zoontek Will this also fix the logo not appearing on the Splash screen when launching the App for the first time?  this happens on release builds.

**Comment by nhutph** [comment]
every things on beta oke man ?

**Comment by anuj1357** [comment]
> every things on beta oke man ?

I don't think there is any beta release yet.

**Comment by zoontek** [comment]
@nhutph @anuj1357 Yes, yes. I worked on it all weekend, please don't add unnecessary pressure. I just need to update the documentation and the migration guide and will do the release.

**Comment by zoontek** [comment]
Hi all 👋
The first beta of v5 is here: https://github.com/zoontek/react-native-bootsplash/pull/475

**Comment by phuongnguyenzoi** [comment]
@zoontek I just tried your @next version, but it still showing black screen when I first install app.

Any idea on this one?

**Comment by zoontek** [comment]
Version 5.0.0 is available: https://github.com/zoontek/react-native-bootsplash/releases/tag/5.0.0

**Comment by dppo** [comment]
The latest version 5.0.0 still has this issue, which crashes when the app is first installed and opened.

My replication devices are Samsung S22 and Android 13

The error log is as follows

`
android.view.WindowLeaked: Activity com.yunlumobile.MainActivity has leaked window DecorView@c169646[MainActivity] that was originally added here
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1322)
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1297)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:530)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
                                                                                                    	at android.app.Dialog.show(Dialog.java:521)
                                                                                                    	at com.zoontek.rnbootsplash.RNBootSplashModuleImpl$4.run(RNBootSplashModuleImpl.java:123)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
`

`
FATAL EXCEPTION: main
                                                                                                    Process: com.yunlumobile, PID: 31587
                                                                                                    java.lang.IllegalArgumentException: View=DecorView@c169646[MainActivity] not attached to window manager
                                                                                                    	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:733)
                                                                                                    	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:619)
                                                                                                    	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:206)
                                                                                                    	at android.app.Dialog.dismissDialog(Dialog.java:809)
                                                                                                    	at android.app.Dialog.dismiss(Dialog.java:791)
                                                                                                    	at com.zoontek.rnbootsplash.RNBootSplashModuleImpl$5$2.onShow(RNBootSplashModuleImpl.java:167)
                                                                                                    	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1916)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
`

The second error is the cause of the crash

The screenshot is as follows
![WX20230823-141357@2x](https://github.com/zoontek/react-native-bootsplash/assets/85061291/f92b5148-079f-4ecb-ae6c-67e77d058522)
![WX20230823-141409@2x](https://github.com/zoontek/react-native-bootsplash/assets/85061291/92c99680-e242-46ee-a6f9-6ddafdb46445)

**Comment by dppo** [comment]
Replenish
On my Samsung S22 device, when it is installed and opened for the first time, BootSplash will be automatically closed, and there is no need to call BootSplash.hide
The reason for the crash is that BootSplash.hide is called after BootSplash is automatically closed

**Comment by zoontek** [comment]
@dppo Looks like a bad install. Can you provide a reproduction repository?

**Comment by dppo** [comment]
> @dppo Can you provide a reproduction repository? Are you using fade: true?

I used a new project to test, although there is no crash phenomenon, but there is still an abnormal situation, the specific situation is as follows.
1. Use react-native 0.72.4
2. newArchEnabled=true
3. Use react-navigation and react-native-bootsplash

In this case, install and start normally for the first time

5. Add react-native-bars
6. Modify the styles file

When installing and starting for the first time, there is an exception displayed, and the exception is as follows


https://github.com/zoontek/react-native-bootsplash/assets/85061291/b5485e5f-c77a-4b23-866f-3b1e6fc8bcb7



Code repository：[Demo](https://github.com/dppo/BootSplashDemo.git)

**Comment by zoontek** [comment]
@dppo I tried to reproduce it by cloning your repository, but no issue at all with my Pixel 4a / Android emulators. My guess is that it might be a Samsung only issue (and I don't have a physical Samsung phone / Samsung don't release ROMs 😕)

You probably have an issue in your logcat when this occur. Could you publish it? Also, which Android version run on your Samsung S22?

**Comment by dppo** [comment]
> @dppo I tried to reproduce it by cloning your repository, but no issue at all with my Pixel 4a / Android emulators. My guess is that it might be a Samsung only issue (and I don't have a physical Samsung phone / Samsung don't release ROMs 😕)
> 
> You probably have an issue in your logcat when this occur. Could you publish it? Also, which Android version run on your Samsung S22?
> 
> Does this occur when you remove some libs? (ex: without bars, without navigation, etc)

1. The Android version is 13, and another device in my hand is normal, so it should be a problem unique to Samsung phones
2. There is a screenshot attached to the answer of the crash log
3. The test code didn't crash, it just displayed an exception, so there are no related logs
4. React-native-bars is not installed. It is normal to test the first installation and open, so guess that there should be a conflict between react-native-bootsplash and react-native-bars

**Comment by dppo** [comment]
I noticed that you just released version 5.0.1. After updating my project, I still have this problem. The following is my Android studio log. I don’t know if it will help you to fix the problem.

[log](https://github.com/zoontek/react-native-bootsplash/files/12424487/log.log)

**Comment by anuj1357** [comment]
@dppo can you confirm if after updating to 5.0.2 your problem is solved? I tried replicating it on a Samsung S22 Android 12, and it seems working for me.

**Comment by w3company-leo** [comment]
any updates? i have this issue after upgrade bootsplash version

**Comment by anuj2285** [comment]
const hideSplash = () => {
    setTimeout(() => BootSplash.hide(), 2000);
  };
  
  <NavigationContainer
        onReady={hideSplash}>
        ...
      </NavigationContainer>

**Comment by c-info** [comment]
Having same issue even on emulators 

show black window and splash hide automatically immediately after 1 or 2 seconds

**Comment by DakshAg62** [comment]
I am facing an issue that, When the splash screen opens the logo appears in a circle then after that it appears normally.
Here is my styles.xml file
<resources xmlns:tools="http://schemas.android.com/tools">

    
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        

        
        
    </style>

    <style name="BootTheme" parent="Theme.BootSplash">
        <item name="bootSplashBackground">@color/black</item>
        <item name="bootSplashLogo">@drawable/splash</item>
        <item name="postBootSplashTheme">@style/AppTheme</item>
    </style>

    <style name="TransparentNavBar" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:navigationBarColor">@android:color/black</item>
        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name ="android:statusBarColor">@android:color/black</item>

        
    </style>
</resources>

**Comment by zoontek** [comment]
@DakshAg62 Read the warnings in your console when generating the assets.
