### ISSUE TITLE
[v5] Android 5 crash

### ISSUE THREAD

**Issue by gollobo** [zoontek/react-native-bootsplash#479]
### Bug summary

Hi! I'm testing the new version v5, and it crashes in all the projects where I've updated the library if the device is running Android 5.0.1 or 5.1.1, especially on Samsung and LG devices. I know this Android version is quite old already, but I don't want to lose users. This crash didn't exist in v4. Thank you very much for this awesome library

### Library version

5-rc0

### Environment info

```shell
System:
  OS: macOS 13.4.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 5.80 GB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.4.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.7.2
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.07.10.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.19
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. Run the app in Android 5 device

### Reproducible sample code

```js
Fatal Exception: android.content.res.Resources$NotFoundException: File res/drawable/compat_splash_screen.xml from drawable resource ID #0x7f070090
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2590)
       at android.content.res.Resources.loadDrawable(Resources.java:2487)
       at android.content.res.Resources.getDrawable(Resources.java:814)
       at android.content.Context.getDrawable(Context.java:403)
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3777)
       at com.android.internal.policy.impl.PhoneWindowEx.generateLayout(PhoneWindowEx.java:22)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3824)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:2000)
       at android.app.Dialog.show(Dialog.java:283)
       at com.zoontek.rnbootsplash.RNBootSplashModuleImpl$4.run(RNBootSplashModuleImpl.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

Caused by org.xmlpull.v1.XmlPullParserException: Binary XML file line #17: <bitmap> requires a valid src attribute
       at android.graphics.drawable.BitmapDrawable.verifyState(BitmapDrawable.java:742)
       at android.graphics.drawable.BitmapDrawable.inflate(BitmapDrawable.java:730)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1128)
       at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:204)
       at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:145)
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1128)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1032)
       at android.content.res.Resources.loadDrawableForCookie(Resources.java:2575)
       at android.content.res.Resources.loadDrawable(Resources.java:2487)
       at android.content.res.Resources.getDrawable(Resources.java:814)
       at android.content.Context.getDrawable(Context.java:403)
       at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3777)
       at com.android.internal.policy.impl.PhoneWindowEx.generateLayout(PhoneWindowEx.java:22)
       at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3824)
       at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:2000)
       at android.app.Dialog.show(Dialog.java:283)
       at com.zoontek.rnbootsplash.RNBootSplashModuleImpl$4.run(RNBootSplashModuleImpl.java)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5422)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by zoontek** [comment]
@gollobo It appears that Android 5.x does not supports `@null` as bitmap src (the default value for the brand image, which you aren't using), making it crashes when this one is not defined on this version.

I added a fallback with a transparent pixel for this specific case, update to `5.0.0-rc.1` to fix the issue.
