### ISSUE TITLE
WindowManager: android.view.WindowLeaked

### ISSUE THREAD

**Issue by Crare** [zoontek/react-native-bootsplash#498]
### Bug summary

Hi! Got error on Android API level 25 (Android 7.1.1) emulator.
This works fine on newer android API level 33.

using react-native 0.72.4.

we get this error in adb logcat:

```
10-18 15:23:45.691 21590 21590 E WindowManager: 
10-18 15:23:45.691 21590 21590 E WindowManager: android.view.WindowLeaked: Activity com.foobar.foobarapp.MainActivity has leaked window DecorView@d90b893[] that was originally added here
10-18 15:23:45.691 21590 21590 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at android.app.Dialog.show(Dialog.java:322)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at com.zoontek.rnbootsplash.RNBootSplashModuleImpl.showDialog(RNBootSplashModuleImpl.java:63)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at com.zoontek.rnbootsplash.RNBootSplashModuleImpl.-$$Nest$smshowDialog(RNBootSplashModuleImpl.java)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at com.zoontek.rnbootsplash.RNBootSplashModuleImpl$5.run(RNBootSplashModuleImpl.java:166)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:751)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at android.os.Looper.loop(Looper.java:154)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
10-18 15:23:45.691 21590 21590 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

### Library version

5.0.4

### Environment info

```shell
System:
  OS: macOS 13.6
  CPU: (10) arm64 Apple M1 Max
  Memory: 408.52 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.8.1
    path: /var/folders/jv/vgxybjb50cq62gfjwnfp386c0000gn/T/yarn--1697632897504-0.23897261438769646/node
  Yarn:
    version: 1.22.19
    path: /var/folders/jv/vgxybjb50cq62gfjwnfp386c0000gn/T/yarn--1697632897504-0.23897261438769646/yarn
  npm:
    version: 10.1.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.10.09.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/<username>/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/<username>/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. use android api level 25.(Android 7.1.1.) emulator. I used device: Nexus 4 API 25, arm64, with Google APIs.
2. use react-native 0.72.4
3. ...

### Reproducible sample code

```js
I tried to do a separate project with just including package react-native-bootsplash and setting it up, but didn't get the error that time. It worked just fine. Our project uses react-navigation-npm package. We changed the app to use smaller splashscreen images as we got some out of memory exceptions. Those do happen sometimes still.

If the splashscreen images were SVG-files, they would use a lot less space too, but they are converted to PNGs.(probably because backwards combatibility or how Android SplashScreen just works?)
```

**Comment by zoontek** [comment]
> I tried to do a separate project with just including package react-native-bootsplash and setting it up, but didn't get the error that time. It worked just fine. Our project uses react-navigation-npm package. We changed the app to use smaller splashscreen images as we got some out of memory exceptions. Those do happen sometimes still.

If you cannot reproduce it easily, this could also be because of another libraries.

> If the splashscreen images were SVG-files, they would use a lot less space too, but they are converted to PNGs.(probably because backwards combatibility or how Android SplashScreen just works?)

Nah, PNGs impact here is really minor.

Do you have a proper way to reproduce it? Or does it happens 100% of the time, at start?

**Comment by zoontek** [comment]
@Crare Should be fixed with https://github.com/zoontek/react-native-bootsplash/pull/505

**Comment by Crare** [comment]
Very nice! I'll try it out as soon as I can. maybe already tomorrow.

**Comment by Crare** [comment]
@zoontek that seems to get rid of the error android.view.WindowLeaked error. Thanks!
we do have other packages though that seem to still break it, but for this part it is ok now.

**Comment by 1280103995** [comment]
```
android.view.WindowLeaked: Activity com.app.MainActivity has leaked window DecorView@87d2fc9[] that was originally added here
    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:417)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
    at android.app.Dialog.show(Dialog.java:316)
    at com.zoontek.rnbootsplash.RNBootSplashDialog.show(RNBootSplashDialog.kt:52)
    at com.zoontek.rnbootsplash.RNBootSplashModuleImpl.init$lambda$2(RNBootSplashModuleImpl.kt:109)
    at com.zoontek.rnbootsplash.RNBootSplashModuleImpl.$r8$lambda$yq3KYLZ0ETFo4io2Y1Z55Z-5PiQ(RNBootSplashModuleImpl.kt)
    at com.zoontek.rnbootsplash.RNBootSplashModuleImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```
I still have this problem. RN v078.2, bootsplash v6.3.3

**Comment by meckanism** [comment]
I'm having the same error on RN  0.72.17 with bootsplash 6.0.0 and APi level 27 (Android 8.1)
```shell
2025-07-07 12:41:35.196  7767-7767  WindowManager           my.cool.namespace E
                                                                                                    android.view.WindowLeaked: Activity tl.bnu.bnutimor.MainActivity has leaked window DecorView@d2463a5[] that was originally added here
                                                                                                    	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
                                                                                                    	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                                                    	at android.app.Dialog.show(Dialog.java:330)
                                                                                                    	at com.zoontek.rnbootsplash.RNBootSplashDialog.show(RNBootSplashDialog.java:92)
                                                                                                    	at com.zoontek.rnbootsplash.RNBootSplashModuleImpl$3.run(RNBootSplashModuleImpl.java:130)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:790)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:164)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
