### ISSUE TITLE
Dialog `dismiss` on a null object reference

### ISSUE THREAD

**Issue by huextrat** [zoontek/react-native-bootsplash#510]
### Bug summary

We are getting crash on v5.1.1

`Attempt to invoke virtual method 'void com.zoontek.rnbootsplash.RNBootSplashDialog.dismiss(java.lang.Runnable)' on a null object reference
mechanism
UncaughtExceptionHandler
handled
`

### Library version

5.1.1

### Environment info

```shell
"react-native": "0.72.6"`
```

### Steps to reproduce

No repro for now but we have a standard impl of RNBootSplash.
Don't have much information about that issue, I will edit it when I have more info

### Reproducible sample code

```js
/
```

**Comment by efstathiosntonas** [comment]
Same here, full stacktrace, Android 13, Samsung devices and some Pixels

```log
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.zoontek.rnbootsplash.RNBootSplashDialog.dismiss(java.lang.Runnable)' on a null object reference
        at com.zoontek.rnbootsplash.RNBootSplashModuleImpl$4$2.run(RNBootSplashModuleImpl.java:196)
        at com.zoontek.rnbootsplash.RNBootSplashDialog$2.onShow(RNBootSplashDialog.java:91)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8762)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by zoontek** [comment]
Could you try this? https://github.com/zoontek/react-native-bootsplash/releases/tag/5.1.2

**Comment by claudiozam** [comment]
Samsung S10 - Android 12 - OK
Samsung S20 Notes - Android 13 - OK

**Comment by claudiozam** [comment]
@zoontek 
Samsung SM-A546E - Android 13 - Error
Samsung SM-G990E - Android 13 - Error

**Comment by huextrat** [comment]
Still some errors on `SM-A145R`, `Huawei P Smart Z`, `Galaxy A13` and there are few Android OS (13, 12, 10, 9)

**Comment by mertafor** [comment]
Crashes also reported by our customers. Our app works on RN 72.7 and Bootsplash 5.1.4. Previously had no issues with 5.0.4 on both Android and IOS:

Affected device (Play Console report): 
**samsung m31 (Galaxy M31) - Android 12 (SDK 31)**

```
Exception java.lang.NullPointerException:
  at com.zoontek.rnbootsplash.RNBootSplashModuleImpl$4$3.run (RNBootSplashModuleImpl.java:213)
  at com.zoontek.rnbootsplash.RNBootSplashDialog$2.onShow (RNBootSplashDialog.java:87)
  at android.app.Dialog$ListenersHandler.handleMessage (Dialog.java:1831)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8663)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:567)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
```

**Comment by mertafor** [comment]
I've been able get my hands on a Redmi 8 with Android 11 (one of the devices have this problem). I've been using `bootsplash.hide()` function with `NavigationContainer` of React Navigation:

```
 onReady={() => {
    RNBootSplash.hide({ fade: true }).catch(() => 0) // catch for TS complaint
 }}
```

I tried to put 500ms delay for Android, then it started work just fine:
```
 onReady={() => {
      if (Platform.OS === 'android') {
        setTimeout(() => {
          RNBootSplash.hide({ fade: true }).catch(() => 0)
        }, 500)
        return
      }
      RNBootSplash.hide({ fade: true }).catch(() => 0)
 }}
```

This might be related to recent React Navigation update. But at least this helps to fix the issue for now.

**Comment by zoontek** [comment]
It should fix it: https://github.com/zoontek/react-native-bootsplash/releases/tag/5.1.3

**Comment by huextrat** [comment]
Thank you @zoontek, I'm closing as version `5.1.3` solved the issue
