### ISSUE TITLE
Android crashes at launch

### ISSUE THREAD

**Issue by handoff** [zoontek/react-native-bootsplash#72]
### 💻 My environment

- react-native-bootsplash version: 2.0.5
- react-native version: 0.61.5
- Platform: android
- OS version: 5.1, 9
- Device: ASUS HW, Samsung Emulator
- Simulator: yes & no
- Android Studio version: 3.5.3
- Android buildToolsVersion: 28.0.3

### 🕵️‍♂️ Reproducing the issue

App crashes before launch. 

Running logcat I can see 
```
E/AndroidRuntime(26536): FATAL EXCEPTION: main
E/AndroidRuntime(26536): Process: se.myapp, PID: 26536
E/AndroidRuntime(26536): java.lang.RuntimeException: Unable to instantiate application se.myapp.MainApplication: java.lang.ClassNotFoundException: Didn't find class "se.myapp.MainApplication" on path: DexPathList[[zip file "/data/app/se.myapp-2/base.apk"],nativeLibraryDirectories=[/data/app/se.myapp-2/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(26536): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:572)
E/AndroidRuntime(26536): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4831)
E/AndroidRuntime(26536): 	at android.app.ActivityThread.access$1500(ActivityThread.java:178)
E/AndroidRuntime(26536): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
E/AndroidRuntime(26536): 	at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime(26536): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime(26536): 	at android.app.ActivityThread.main(ActivityThread.java:5637)
E/AndroidRuntime(26536): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(26536): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(26536): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
E/AndroidRuntime(26536): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
E/AndroidRuntime(26536): Caused by: java.lang.ClassNotFoundException: Didn't find class "se.myapp.MainApplication" on path: DexPathList[[zip file "/data/app/se.myapp-2/base.apk"],nativeLibraryDirectories=[/data/app/se.myapp-2/lib/arm, /vendor/lib, /system/lib]]
E/AndroidRuntime(26536): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime(26536): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime(26536): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime(26536): 	at android.app.Instrumentation.newApplication(Instrumentation.java:985)
E/AndroidRuntime(26536): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:567)
E/AndroidRuntime(26536): 	... 10 more
E/AndroidRuntime(26536): 	Suppressed: java.lang.ClassNotFoundException: se.myapp.MainApplication
E/AndroidRuntime(26536): 		at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(26536): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime(26536): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime(26536): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime(26536): 		... 13 more
E/AndroidRuntime(26536): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

My MainActivity.java
```
package se.myapp;

import android.os.Bundle;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactActivityDelegate;
import com.facebook.react.ReactRootView;
import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

import com.zoontek.rnbootsplash.RNBootSplash; 

public class MainActivity extends ReactActivity {

  /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
    return "myapp";
  }

  @Override
  protected ReactActivityDelegate createReactActivityDelegate() {
    return new ReactActivityDelegate(this, getMainComponentName()) {
      @Override
      protected ReactRootView createRootView() {
        return new RNGestureHandlerEnabledRootView(MainActivity.this);
      }
    };
  }

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    RNBootSplash.init(R.drawable.bootsplash, MainActivity.this); // <- display the generated bootsplash.xml drawable over our MainActivity
  }
}
```

My AndroidManifest.xml

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="se.myapp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="com.android.vending.BILLING" />
    
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">

      <meta-data
        android:name="com.google.android.geo.API_KEY"
        android:value="xxx"
      />

      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>

      <activity
        android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
        android:theme="@style/BootTheme"> 
        <intent-filter>
          <action android:name="android.intent.action.MAIN" />
          <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>

      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />

    </application>

</manifest>
```

**Comment by zoontek** [comment]
Enable Multidex: https://developer.android.com/studio/build/multidex
Then clean the build folder `./gradlew clean`. Build again.

**Comment by handoff** [comment]
I have my minSdk set to 21. Following the link I can read:

"If your minSdkVersion is set to 21 or higher, multidex is enabled by default and you do not need the multidex support library."

**Comment by zoontek** [comment]
Then just do a Gradle clean.
But the error is not really tied to this lib.

**Comment by handoff** [comment]
Weird, but probably try. Thank you for you suggestions.

**Comment by wibb36** [comment]
I'm having the same issue. Android shows the splash then crashes the moment is ready.

**Comment by Vasault** [comment]
having the same issue, i can react-native run-android and see the result, but once i close the app, and manually open it from the device (or emulator, doesn't matter) immediately crashes

**Comment by wadeyw** [comment]
Hi, may I check how did you guys sovle the issue last time? now I just upgrade to react native 0.71.2, have the same issue as @Vasault described, error is java.lang.ClassNotFoundException: Didn't find class "com.zoontek.rnbootsplash.RNBootSplashActivity" on path: DexPathList , just clean up seems not working

**Comment by zoontek** [comment]
@wadeyw `RNBootSplashActivity` doesn't exist in the v4 of this library, the only version to officially support react native 0.65+ https://github.com/zoontek/react-native-bootsplash#support
